#!/usr/bin/env python3
"""Discover coding-agent sessions across Claude Code, Codex, Cursor (IDE + CLI), and Pi
within a time window, and emit a compact JSON inventory grouped by project / git-worktree.

This emits METADATA + light activity signals only -- never full transcripts -- so the
result is small and safe to load into a reasoning model's context. Deep per-session
content is the job of extract_session.py, run only on the sessions worth a closer look.

Storage locations (macOS/Linux):
  claude     ~/.claude/projects/<enc-cwd>/<session-id>.jsonl
  codex      ~/.codex/sessions/YYYY/MM/DD/rollout-*.jsonl  (+ ~/.codex/archived_sessions)
  cursor-cli ~/.cursor/projects/<enc-cwd>/agent-transcripts/<uuid>/<uuid>.jsonl
  cursor-ide ~/.cursor/chats/<ws-hash>/<chat-uuid>/store.db   (SQLite: blobs + meta)
  pi         ~/.pi/agent/sessions/--<enc-cwd>--/<ts>_<uuid>.jsonl
See references/session-formats.md for the field-level schema of each.

Usage:
  discover_sessions.py [WINDOW] [--agents claude,codex,cursor,pi] [--json OUT] [--summary]
WINDOW (choose one; default --yesterday):
  --yesterday | --today | --days N | --week | --since ISO --until ISO
"""
import argparse, glob, json, os, re, sqlite3, subprocess, sys, time
from datetime import datetime, timedelta, timezone
from pathlib import Path

HOME = Path.home()
MAX_ASK = 300

# ----------------------------- time helpers -----------------------------
def to_epoch(iso):
    if not iso:
        return None
    try:
        return datetime.fromisoformat(str(iso).strip().replace("Z", "+00:00")).timestamp()
    except Exception:
        return None

def iso(epoch):
    if epoch is None:
        return None
    return datetime.fromtimestamp(epoch, tz=timezone.utc).astimezone().isoformat(timespec="seconds")

def resolve_window(args):
    now = datetime.now().astimezone()
    midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)
    if args.since or args.until:
        start = to_epoch(args.since) if args.since else (midnight - timedelta(days=1)).timestamp()
        end = to_epoch(args.until) if args.until else now.timestamp()
        return start, end, "custom"
    if args.today:
        return midnight.timestamp(), now.timestamp(), "today"
    if args.week:
        return (now - timedelta(days=7)).timestamp(), now.timestamp(), "last 7 days"
    if args.days is not None:
        return (now - timedelta(days=args.days)).timestamp(), now.timestamp(), f"last {args.days} days"
    # default: yesterday (local calendar day)
    return (midnight - timedelta(days=1)).timestamp(), midnight.timestamp(), "yesterday"

# ----------------------------- text helpers -----------------------------
def clip(s, n=MAX_ASK):
    if s is None:
        return None
    s = re.sub(r"\s+", " ", str(s)).strip()
    return s[:n] + ("…" if len(s) > n else "")

TAG_RE = re.compile(r"<(user_info|environment_details|system_info|additional_data)>.*?</\1>", re.S)
WS_PATH_RE = re.compile(r"Workspace Path:\s*(/[^\n]+)")

def text_from_content(content):
    """Flatten a message 'content' (str | list-of-blocks | dict) into plain text."""
    if content is None:
        return ""
    if isinstance(content, str):
        return content
    out = []
    if isinstance(content, list):
        for b in content:
            if isinstance(b, dict):
                if "text" in b and isinstance(b["text"], str):
                    out.append(b["text"])
                elif b.get("type") == "tool_result" and isinstance(b.get("content"), (str, list)):
                    pass  # skip tool output (guardrail)
            elif isinstance(b, str):
                out.append(b)
    elif isinstance(content, dict):
        if "text" in content:
            out.append(str(content["text"]))
    return "\n".join(out)

def clean_ask(text):
    """Pull the real human ask out of a (possibly tag-wrapped) user message."""
    if not text:
        return ""
    m = re.search(r"<user_query>(.*?)</user_query>", text, re.S)
    if m:
        text = m.group(1)
    return TAG_RE.sub(" ", text).strip()

def is_boilerplate(text):
    t = (text or "").lstrip()
    if not t:
        return True
    low = t[:240].lower()
    if t.startswith(("<user_info", "<environment", "<system-reminder", "<command-name", "<command-message")):
        return "<user_query>" not in t
    if "caveat: the messages below were generated by the user while running" in low:
        return True
    if t.startswith("[Request interrupted") or t.startswith("API Error") or t.startswith("<local-command-stdout"):
        return True
    return False

CMD_RE = re.compile(r"<command-(?:name|message)>\s*([^<]+?)\s*</command-")
ARGS_RE = re.compile(r"<command-args>(.*?)</command-args>", re.S)
def slash_command(text):
    """Recover a slash-command invocation (name + args) from a command-caveat wrapper."""
    m = CMD_RE.search(text or "")
    if not m:
        return None
    name = m.group(1).strip().lstrip("/")
    a = ARGS_RE.search(text or "")
    args = clip(a.group(1).strip(), 160) if (a and a.group(1).strip()) else ""
    return f"/{name} {args}".strip()

def extract_ask(raw):
    """Return (ask, kind_hint) from a raw user message; (None, None) if pure boilerplate."""
    if raw is None:
        return None, None
    cmd = slash_command(raw)
    if cmd:
        return cmd, "command"
    if is_boilerplate(raw):
        return None, None
    ask = clean_ask(raw)
    return (ask or None), None

CONTROL_CMDS = ("/exit", "/quit", "/clear", "/model", "/effort", "/compact", "/resume",
                "/config", "/help", "/login", "/logout", "/status", "/cost", "/init",
                "/agents", "/context", "/fast", "/mcp", "/doctor", "/vim", "/terminal-setup")
def classify(rec):
    """Activity-aware session kind. A leading skill-command that then did real work is
    'interactive', not 'command'; only control-only no-op sessions are 'control'."""
    ask = rec.get("first_ask") or ""
    al = ask.lower()
    tools, ut = rec.get("tool_calls", 0), rec.get("user_turns", 0)
    if ask.startswith(CONTROL_CMDS) and tools == 0 and ut <= 2:
        return "control"
    if al.startswith("automation:") or "automation id:" in al:
        return "automation"
    if "review guidelines" in al or al.startswith("## code review") or "you are acting as a rev" in al:
        return "review"
    if al.startswith(("you are doing one bounded", "you are an expert", "you are a ", "you are acting")):
        return "agentic-prompt"
    return "interactive"

def record_user(rec, raw):
    """Register a user turn on a session record, filtering boilerplate."""
    ask, _ = extract_ask(raw)
    if not ask:
        return
    rec["user_turns"] += 1
    if not rec["first_ask"]:
        rec["first_ask"] = ask
    rec["last_ask"] = ask

def workspace_from_text(text):
    m = WS_PATH_RE.search(text or "")
    return m.group(1).strip() if m else None

# ----------------------------- git/project grouping -----------------------------
_git_cache = {}
def git_common_dir(path):
    """Return the realpath of a repo's shared .git dir, unifying all its worktrees.
    None when path is gone or not a git repo."""
    if not path:
        return None
    if path in _git_cache:
        return _git_cache[path]
    res = None
    try:
        if os.path.isdir(path):
            r = subprocess.run(["git", "-C", path, "rev-parse", "--git-common-dir"],
                               capture_output=True, text=True, timeout=4)
            if r.returncode == 0 and r.stdout.strip():
                gd = r.stdout.strip()
                if not os.path.isabs(gd):
                    gd = os.path.abspath(os.path.join(path, gd))
                res = os.path.realpath(gd)
    except Exception:
        res = None
    _git_cache[path] = res
    return res

def repo_root(common):
    if not common:
        return None
    if common.endswith("/.git"):
        return common[:-5]
    if "/.git/worktrees/" in common:
        return common.split("/.git/")[0]
    if "/.git" in common:
        return common.split("/.git")[0]
    return os.path.dirname(common)

def project_grouping(path):
    """Return (group_key, label). Worktrees of one repo share a group_key."""
    common = git_common_dir(path)
    if common:
        root = repo_root(common)
        return common, (os.path.basename(root.rstrip("/")) if root else os.path.basename(path or ""))
    if path:
        return os.path.realpath(path) if os.path.isdir(path) else path, os.path.basename(path.rstrip("/")) or path
    return "(unknown)", "(unknown)"

def decode_dir_name(name):
    """Best-effort decode of an enc-cwd dir name back to a path label (slashes are lossy)."""
    n = name.strip("-")
    if not n:
        return None
    return "/" + n.replace("-", "/")

# ----------------------------- per-agent scanners -----------------------------
def _new_rec(agent, sid, file):
    return {"agent": agent, "session_id": sid, "file": file, "project_path": None,
            "worktree": None, "branch": None, "model": None, "title": None,
            "first_ask": None, "last_ask": None, "start_ts": None, "end_ts": None,
            "user_turns": 0, "assistant_turns": 0, "tool_calls": 0, "files_touched": 0,
            "signals": {"completed": False, "ended_mid_tool": False, "had_errors": False,
                        "compacted": False, "web_search": False},
            "size_bytes": None, "lines": 0}

def _finish(rec):
    s = rec.pop("_start", None)
    e = rec.pop("_end", None)
    rec["start_ts"], rec["end_ts"] = iso(s), iso(e)
    rec["duration_min"] = round((e - s) / 60) if (s and e and e >= s) else None
    rec["first_ask"] = clip(rec["first_ask"])
    rec["last_ask"] = clip(rec["last_ask"])
    rec["title"] = clip(rec.get("title"), 120)
    try:
        rec["size_bytes"] = os.path.getsize(rec["file"])
    except Exception:
        pass
    grp, label = project_grouping(rec["project_path"])
    rec["group_key"], rec["project_label"] = grp, label
    if rec["worktree"] is None and rec["project_path"]:
        rec["worktree"] = os.path.basename(rec["project_path"].rstrip("/"))
    rec["kind"] = classify(rec)
    return rec

def _track_ts(rec, ts):
    e = to_epoch(ts)
    if e is None:
        return
    if rec.get("_start") is None or e < rec["_start"]:
        rec["_start"] = e
    if rec.get("_end") is None or e > rec["_end"]:
        rec["_end"] = e

def scan_claude(win_start, win_end):
    out = []
    for f in glob.glob(str(HOME / ".claude/projects/*/*.jsonl")):
        try:
            if os.path.getmtime(f) < win_start - 86400:
                continue
        except Exception:
            continue
        rec = _new_rec("claude", Path(f).stem, f)
        last_assistant_tooluse = False
        try:
            for line in Path(f).read_text(errors="replace").splitlines():
                rec["lines"] += 1
                try:
                    d = json.loads(line)
                except Exception:
                    continue
                t = d.get("type")
                if "timestamp" in d:
                    _track_ts(rec, d["timestamp"])
                if d.get("cwd"):
                    rec["project_path"] = d["cwd"]
                if d.get("gitBranch"):
                    rec["branch"] = d["gitBranch"]
                if t == "ai-title" and d.get("aiTitle"):
                    rec["title"] = d["aiTitle"]
                elif t == "user":
                    msg = d.get("message", {}) or {}
                    record_user(rec, text_from_content(msg.get("content")))
                    last_assistant_tooluse = False
                elif t == "assistant":
                    rec["assistant_turns"] += 1
                    msg = d.get("message", {}) or {}
                    if msg.get("model"):
                        rec["model"] = msg["model"]
                    blocks = msg.get("content") or []
                    had_tool = False
                    if isinstance(blocks, list):
                        for b in blocks:
                            if isinstance(b, dict) and b.get("type") == "tool_use":
                                rec["tool_calls"] += 1
                                had_tool = True
                                if b.get("name") in ("Edit", "Write", "MultiEdit", "NotebookEdit"):
                                    rec["files_touched"] += 1
                    last_assistant_tooluse = had_tool
                elif t == "system":
                    if d.get("subtype") == "compact" or "compact" in str(d.get("subtype", "")):
                        rec["signals"]["compacted"] = True
                    if d.get("level") == "error" or d.get("hookErrors"):
                        rec["signals"]["had_errors"] = True
        except Exception:
            continue
        if rec.get("_end") is None or rec["_end"] < win_start or rec.get("_start", 0) > win_end:
            continue
        rec["signals"]["ended_mid_tool"] = last_assistant_tooluse
        out.append(_finish(rec))
    return out

def scan_codex(win_start, win_end):
    out = []
    roots = [HOME / ".codex/sessions", HOME / ".codex/archived_sessions"]
    files = []
    for r in roots:
        if r.exists():
            files += glob.glob(str(r / "**/*.jsonl"), recursive=True)
    for f in files:
        try:
            if os.path.getmtime(f) < win_start - 86400:
                continue
        except Exception:
            continue
        rec = _new_rec("codex", None, f)
        last_call_open = False
        try:
            for line in Path(f).read_text(errors="replace").splitlines():
                rec["lines"] += 1
                try:
                    d = json.loads(line)
                except Exception:
                    continue
                t = d.get("type")
                p = d.get("payload", {}) or {}
                if d.get("timestamp"):
                    _track_ts(rec, d["timestamp"])
                if t == "session_meta":
                    rec["session_id"] = p.get("id")
                    rec["project_path"] = p.get("cwd")
                    if p.get("timestamp"):
                        _track_ts(rec, p["timestamp"])
                elif t == "turn_context":
                    rec["model"] = rec["model"] or p.get("model") or p.get("model_slug")
                    if p.get("cwd"):
                        rec["project_path"] = rec["project_path"] or p["cwd"]
                elif t == "event_msg":
                    pt = p.get("type")
                    if pt == "user_message":
                        record_user(rec, p.get("message") or text_from_content(p.get("content")))
                    elif pt == "agent_message":
                        rec["assistant_turns"] += 1
                    elif pt == "task_complete":
                        rec["signals"]["completed"] = True
                    elif pt == "patch_apply_end":
                        rec["files_touched"] += 1
                    elif pt in ("web_search_end", "web_search_call"):
                        rec["signals"]["web_search"] = True
                    elif pt == "context_compacted":
                        rec["signals"]["compacted"] = True
                    elif pt == "error":
                        rec["signals"]["had_errors"] = True
                elif t == "response_item":
                    pt = p.get("type")
                    if pt == "function_call":
                        rec["tool_calls"] += 1
                        last_call_open = True
                    elif pt == "function_call_output":
                        last_call_open = False
                    elif pt == "custom_tool_call":
                        rec["tool_calls"] += 1
        except Exception:
            continue
        if rec.get("_end") is None or rec["_end"] < win_start or rec.get("_start", 0) > win_end:
            continue
        if not rec["session_id"]:
            rec["session_id"] = Path(f).stem.split("-")[-1]
        rec["signals"]["ended_mid_tool"] = last_call_open
        out.append(_finish(rec))
    return out

def scan_cursor_cli(win_start, win_end):
    out = []
    for f in glob.glob(str(HOME / ".cursor/projects/*/agent-transcripts/*/*.jsonl")):
        try:
            if os.path.getmtime(f) < win_start - 86400:
                continue
        except Exception:
            continue
        mt = os.path.getmtime(f)
        rec = _new_rec("cursor-cli", Path(f).stem, f)
        # cursor-cli transcripts carry no per-line ts; use file mtime as the activity time
        rec["_start"] = mt
        rec["_end"] = mt
        proj_dir = f.split("/agent-transcripts/")[0]
        rec["project_path"] = decode_dir_name(Path(proj_dir).name)
        try:
            for line in Path(f).read_text(errors="replace").splitlines():
                rec["lines"] += 1
                try:
                    d = json.loads(line)
                except Exception:
                    continue
                role = d.get("role")
                msg = d.get("message")
                txt = text_from_content(msg.get("content")) if isinstance(msg, dict) else text_from_content(msg)
                ws = workspace_from_text(txt)
                if ws:
                    rec["project_path"] = ws
                if role == "user":
                    record_user(rec, txt)
                elif role == "assistant":
                    rec["assistant_turns"] += 1
                    if isinstance(msg, dict) and isinstance(msg.get("content"), list):
                        for b in msg["content"]:
                            if isinstance(b, dict) and b.get("type") in ("tool_use", "tool_call", "toolCall"):
                                rec["tool_calls"] += 1
        except Exception:
            continue
        if mt < win_start or mt > win_end:
            continue
        out.append(_finish(rec))
    return out

def scan_cursor_ide(win_start, win_end):
    out = []
    for db in glob.glob(str(HOME / ".cursor/chats/*/*/store.db")):
        try:
            mt = os.path.getmtime(db)
            if mt < win_start or mt > win_end:
                continue
        except Exception:
            continue
        rec = _new_rec("cursor-ide", Path(db).parent.name, db)
        rec["_start"] = mt
        rec["_end"] = mt
        try:
            con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
            for (data,) in con.execute("SELECT data FROM blobs"):
                if not isinstance(data, (bytes, bytearray)):
                    continue
                try:
                    obj = json.loads(bytes(data).decode("utf-8"))
                except Exception:
                    continue  # binary graph blob -> skip
                if not isinstance(obj, dict) or "role" not in obj:
                    continue
                role = obj.get("role")
                txt = text_from_content(obj.get("content"))
                ws = workspace_from_text(txt)
                if ws:
                    rec["project_path"] = ws
                if role == "user":
                    record_user(rec, txt)
                elif role == "assistant":
                    rec["assistant_turns"] += 1
            con.close()
        except Exception:
            continue
        rec["model"] = rec["model"] or "composer"
        out.append(_finish(rec))
    return out

def scan_pi(win_start, win_end):
    out = []
    for f in glob.glob(str(HOME / ".pi/agent/sessions/**/*.jsonl"), recursive=True):
        try:
            if os.path.getmtime(f) < win_start - 86400:
                continue
        except Exception:
            continue
        rec = _new_rec("pi", Path(f).stem.split("_")[-1], f)
        last_open_tool = False
        try:
            for line in Path(f).read_text(errors="replace").splitlines():
                rec["lines"] += 1
                try:
                    d = json.loads(line)
                except Exception:
                    continue
                t = d.get("type")
                if d.get("timestamp"):
                    _track_ts(rec, d["timestamp"])
                if t == "session":
                    rec["project_path"] = d.get("cwd")
                elif t in ("model_change",):
                    rec["model"] = d.get("modelId") or rec["model"]
                elif t == "message":
                    m = d.get("message")
                    if isinstance(m, str):
                        try:
                            m = json.loads(m)
                        except Exception:
                            m = {"role": "user", "content": m}
                    role = (m or {}).get("role")
                    txt = text_from_content((m or {}).get("content"))
                    if role == "user":
                        record_user(rec, txt)
                        last_open_tool = False
                    elif role == "assistant":
                        rec["assistant_turns"] += 1
                        c = (m or {}).get("content")
                        if isinstance(c, list):
                            for b in c:
                                if isinstance(b, dict) and b.get("type") in ("tool_use", "tool_call"):
                                    rec["tool_calls"] += 1
                                    last_open_tool = True
                elif t in ("tool_result", "tool_output"):
                    last_open_tool = False
        except Exception:
            continue
        if rec.get("_end") is None or rec["_end"] < win_start or rec.get("_start", 0) > win_end:
            continue
        rec["signals"]["ended_mid_tool"] = last_open_tool
        out.append(_finish(rec))
    return out

SCANNERS = {"claude": scan_claude, "codex": scan_codex,
            "cursor": [scan_cursor_cli, scan_cursor_ide], "pi": scan_pi}

# ----------------------------- assembly -----------------------------
def build_inventory(agents, win_start, win_end, label, include_noise=False):
    sessions = []
    for a in agents:
        fns = SCANNERS.get(a)
        if not fns:
            continue
        for fn in (fns if isinstance(fns, list) else [fns]):
            try:
                sessions += fn(win_start, win_end)
            except Exception as e:
                print(f"[discover] {a} scan error: {e}", file=sys.stderr)
    sessions.sort(key=lambda r: r.get("end_ts") or "", reverse=True)
    noise_dropped = sum(1 for s in sessions if s["kind"] == "control")
    if not include_noise:
        sessions = [s for s in sessions if s["kind"] != "control"]

    groups = {}
    for s in sessions:
        g = groups.setdefault(s["group_key"], {"project_label": s["project_label"],
                                               "group_key": s["group_key"],
                                               "paths": set(), "branches": set(),
                                               "agents": set(), "sessions": []})
        g["project_label"] = g["project_label"] or s["project_label"]
        if s["project_path"]:
            g["paths"].add(s["project_path"])
        if s["branch"]:
            g["branches"].add(s["branch"])
        g["agents"].add(s["agent"])
        g["sessions"].append(s)
    projects = []
    for g in groups.values():
        projects.append({"project_label": g["project_label"], "group_key": g["group_key"],
                         "paths": sorted(g["paths"]), "branches": sorted(g["branches"]),
                         "agents": sorted(g["agents"]), "session_count": len(g["sessions"]),
                         "worktree_count": len(g["paths"]), "sessions": g["sessions"]})
    projects.sort(key=lambda p: p["session_count"], reverse=True)

    counts = {}
    for s in sessions:
        counts[s["agent"]] = counts.get(s["agent"], 0) + 1
    return {"window": {"start": iso(win_start), "end": iso(win_end), "label": label},
            "generated_at": iso(time.time()),
            "totals": {"sessions": len(sessions), "projects": len(projects),
                       "by_agent": counts, "noise_dropped": noise_dropped},
            "projects": projects, "sessions": sessions}

def print_summary(inv):
    w = inv["window"]
    print(f"\nAGENT STANDUP INVENTORY  ({w['label']}: {w['start']} -> {w['end']})")
    print(f"  {inv['totals']['sessions']} sessions across {inv['totals']['projects']} projects "
          f"| by agent: {inv['totals']['by_agent']}\n")
    for p in inv["projects"]:
        flag = "  ⚠ multi-worktree" if p["worktree_count"] > 1 else ""
        print(f"▸ {p['project_label']}  ({p['session_count']} sessions, "
              f"{p['worktree_count']} worktree(s), agents: {','.join(p['agents'])}){flag}")
        for s in p["sessions"][:12]:
            sig = []
            if s.get("kind") and s["kind"] != "interactive":
                sig.append(s["kind"])
            if s["signals"]["completed"]:
                sig.append("done")
            if s["signals"]["ended_mid_tool"]:
                sig.append("mid-tool")
            if s["signals"]["had_errors"]:
                sig.append("errors")
            if s["signals"]["compacted"]:
                sig.append("compacted")
            wt = f" [{s['branch'] or s['worktree']}]" if (s["branch"] or p["worktree_count"] > 1) else ""
            print(f"    - {s['agent']:<10}{wt} {s['end_ts'] or '?'}  "
                  f"{(s['title'] or s['first_ask'] or '(no ask captured)')[:70]}  "
                  f"<{s['user_turns']}u/{s['tool_calls']}t {'/'.join(sig)}>")
        if len(p["sessions"]) > 12:
            print(f"    ... +{len(p['sessions']) - 12} more")

def main():
    ap = argparse.ArgumentParser(description="Discover agent coding sessions in a time window")
    ap.add_argument("--agents", default="claude,codex,cursor,pi")
    ap.add_argument("--yesterday", action="store_true")
    ap.add_argument("--today", action="store_true")
    ap.add_argument("--week", action="store_true")
    ap.add_argument("--days", type=int)
    ap.add_argument("--since")
    ap.add_argument("--until")
    ap.add_argument("--json", help="write inventory JSON to this path")
    ap.add_argument("--summary", action="store_true", help="print human summary to stdout")
    ap.add_argument("--include-noise", action="store_true", help="keep control-only no-op sessions")
    args = ap.parse_args()

    win_start, win_end, label = resolve_window(args)
    agents = [a.strip() for a in args.agents.split(",") if a.strip()]
    inv = build_inventory(agents, win_start, win_end, label, include_noise=args.include_noise)

    if args.json:
        Path(args.json).write_text(json.dumps(inv, indent=2))
        print(f"[discover] wrote {inv['totals']['sessions']} sessions to {args.json}", file=sys.stderr)
    if args.summary or not args.json:
        print_summary(inv)

if __name__ == "__main__":
    main()
